name: LocalTests
'on':
  pull_request_target:
    types:
    - assigned
    - opened
    - synchronize
    - reopened
    - ready_for_review
  push:
    branches:
    - main
    - future
jobs:
  LocalTests:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - ubuntu-24.04
    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Running Local Tests
      run: '## Install pytest

        pip install pytest

        pytest

        '
